apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhseldon/cluster
      name: odhseldon
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: superset
      name: superset
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: openshift-operators
        repoRef:
          name: custom-manifests
          path: amq-streams/cluster
      name: strimzi-operator
    - kustomizeConfig:
        repoRef:
          name: custom-manifests
          path: amq-streams/kafka
      name: kafka-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/cluster
      name: grafana-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/grafana
      name: grafana-instance
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: radanalyticsio/spark/cluster
      name: radanalyticsio-spark-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/cluster
      name: prometheus-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/operator
      name: prometheus-operator
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: >-
              rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc:80
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/operator
      name: airflow-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/cluster
      name: airflow-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhargo/cluster
      name: odhargo-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhargo/odhargo
      name: odhargo
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: model-mesh
      name: model-mesh
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        repoRef:
          name: custom-manifests
          path: openshift-service-mesh/cluster
      name: openshift-service-mesh
    - kustomizeConfig:
        repoRef:
          name: custom-manifests
          path: openshift-service-mesh-config
      name: openshift-service-mesh-config
    - kustomizeConfig:
        parameters:
          - name: s3_is_secure
            value: 'false'
          - name: s3_endpoint_url
            value: >-
              rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc:80
          - name: s3_credentials_secret
            value: odh-bucket
        repoRef:
          name: manifests
          path: hue/hue
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ai-library/cluster
      name: ai-library-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ai-library/operator
      name: ai-library-operator
  repos:
    - name: kf-manifests
      uri: 'https://github.com/kubeflow/manifests/archive/v1.2-branch.tar.gz'
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/master'
    - name: custom-manifests
      uri: 'https://github.com/pmalan/odh-manifest/tarball/master'
  version: master
status: {}
